### ISSUE TITLE
Query produces more results than required

### ISSUE THREAD

**Issue by jossygru** [linkedfactory/linkedfactory-pod#8]
**Description of the bug**
A query should produce at most an exact number of results (in the example attached "Result.png" maximum 2 results), but the number of output results are more than required.

**To Reproduce**

1. Store the time series data (attached the files linkedfactory-valuestore.zip and jsontimeseriesdtaMaho.json).
2. POST the RDF models (attached the postman collection, containing "Store RDF data" and "Store BAMM meta data").
3. Query some data where is required to show at most 2 results  (attached the postman collection ,containing "Query data as csv").

**Expected behavior**
Output where is required to show at most 2 results.

**Additional information**
It should also be noted that apart from the fact that more data is produced in the results than required, in each additional result the time is missing.

[demonstrator.postman_collection.json](https://github.com/linkedfactory/linkedfactory-pod/files/13510953/demonstrator.postman_collection.json)
[jsontimeseriesdataMaho.json](https://github.com/linkedfactory/linkedfactory-pod/files/13510954/jsontimeseriesdataMaho.json)
[linkedfactory-valuestore.zip](https://github.com/linkedfactory/linkedfactory-pod/files/13510956/linkedfactory-valuestore.zip)
![Result](https://github.com/linkedfactory/linkedfactory-pod/assets/71405272/1d195e1d-badf-480f-acfa-6faa4b49be8e)

**Comment by kenwenzel** [comment]
This is working with the current version. We can re-open it if the issue persists.
